type DemoReply = { handled: boolean; response?: unknown; error?: Error };

const now = '2026-08-27T12:00:00Z';
const operations = {
  summary: { batches: 3, queued_runs: 1, running_runs: 0, failed_runs: 1, active_holds: 1, redactions: 1, purged_files: 0 },
  retention: { retention_days: 365, enabled: true, purge_mode: 'manual_governed', last_run: { finished_at: '2026-08-20T09:30:00Z', dry_run: true, purged_count: 0 } },
  data: [
    { id: 'b4eb89c9-1a75-4583-9e03-1cff77a65c08', document_type: 'purchase_invoice', workflow_status: 'failed', version: 3, created_at: now, updated_at: now, file: { id: 'f4eb89c9-1a75-4583-9e03-1cff77a65c08', scan_status: 'clean', purged_at: null }, processing_status: { key: 'failed_retry_available', tone: 'danger', retry_available: true, message: 'فشلت المعالجة؛ قد تتاح إعادة المحاولة وفق إعدادات المنصة.' }, runs: [{ id: 'r4eb89c9-1a75-4583-9e03-1cff77a65c08', stage: 'extraction', status: 'failed', attempt_count: 1, error_code: 'extraction_failed', error_message_safe: 'فشل الاستخراج بعد استنفاد المحاولات المسموح بها.', updated_at: now }] },
    { id: 'b5eb89c9-1a75-4583-9e03-1cff77a65c08', document_type: 'expense', workflow_status: 'received', version: 2, created_at: now, updated_at: now, file: { id: 'f5eb89c9-1a75-4583-9e03-1cff77a65c08', scan_status: 'clean', purged_at: null }, processing_status: { key: 'extraction_unavailable', tone: 'warning', retry_available: false, message: 'استخراج البيانات غير مفعّل حالياً.' }, runs: [] },
    { id: 'b6eb89c9-1a75-4583-9e03-1cff77a65c08', document_type: 'purchase_invoice', workflow_status: 'needs_review', version: 5, created_at: now, updated_at: now, file: { id: 'f6eb89c9-1a75-4583-9e03-1cff77a65c08', scan_status: 'clean', purged_at: null }, processing_status: { key: 'needs_review', tone: 'warning', retry_available: false, message: 'المستند جاهز للمراجعة البشرية.' }, runs: [{ id: 'r6eb89c9-1a75-4583-9e03-1cff77a65c08', stage: 'safety_scan', status: 'succeeded', attempt_count: 1, error_code: null, error_message_safe: null, updated_at: now }] },
  ],
  meta: { current_page: 1, last_page: 1, total: 3 },
};
const usage = { range: { from: '2026-07-28', to: '2026-08-27' }, operations: 2, pages: 4, input_tokens: 860, output_tokens: 212, total_tokens: 1072, processing_duration_ms: 3480, successful_operations: 2, failed_attempts: 1, cost_available: false, cost_by_currency: [], by_provider_model: [{ provider: 'configured-provider', model: 'safe-model', operations: 2, pages: 4, input_tokens: 860, output_tokens: 212 }] };
let holds: Array<{ id: string; batch_id: string | null; file_id: string | null; reason_code: string; created_at: string; released_at: string | null; release_reason_code: string | null }> = [{ id: 'h4eb89c9-1a75-4583-9e03-1cff77a65c08', batch_id: operations.data[0].id, file_id: null, reason_code: 'legal_review', created_at: now, released_at: null, release_reason_code: null }];
let overlays = [{ id: 'o4eb89c9-1a75-4583-9e03-1cff77a65c08', result_id: 'e4eb89c9-1a75-4583-9e03-1cff77a65c08', field_path: 'fields.issuer_name', reason_code: 'privacy_request', redacted_at: now }];

export function handleDocumentOperationsDemo(path: string, method: string, body?: unknown): DemoReply {
  const clean = path.split('?')[0];
  const input = (body ?? {}) as Record<string, string | boolean | undefined>;
  if (clean === '/document-operations') return { handled: true, response: { data: operations } };
  if (clean === '/document-usage') return { handled: true, response: { data: usage } };
  if (clean === '/document-governance') return { handled: true, response: { data: { policy: { retention_days: 365, enabled: true, purge_mode: 'manual_governed', policy_source: 'config_default', last_run_at: '2026-08-20T09:30:00Z' }, active_holds: holds, redactions: overlays, redaction_fields: ['fields.issuer_name', 'fields.issuer_tax_number', 'fields.recipient_name', 'fields.recipient_tax_number', 'fields.document_number', 'fields.external_reference', 'fields.purchase_order_number', 'lines.*.description', 'lines.*.sku', 'lines.*.barcode'] } } };
  if (clean === '/document-retention-holds' && method === 'POST') { const item = { id: `h-${Date.now()}`, batch_id: typeof input.document_batch_id === 'string' ? input.document_batch_id : null, file_id: typeof input.file_id === 'string' ? input.file_id : null, reason_code: String(input.reason_code ?? 'legal_review'), created_at: now, released_at: null, release_reason_code: null }; holds = [item, ...holds]; return { handled: true, response: { data: item } }; }
  const release = clean.match(/^\/document-retention-holds\/([^/]+)\/release$/);
  if (release && method === 'POST') { holds = holds.filter((item) => item.id !== release[1]); return { handled: true, response: { data: {} } }; }
  if (clean === '/document-redactions' && method === 'POST') { const item = { id: `o-${Date.now()}`, result_id: String(input.document_extraction_result_id ?? ''), field_path: String(input.field_path ?? ''), reason_code: String(input.reason_code ?? ''), redacted_at: now }; overlays = [item, ...overlays]; return { handled: true, response: { data: item } }; }
  if (/^\/document-processing-runs\/[^/]+\/retry$/.test(clean) && method === 'POST') return { handled: true, response: { data: { accepted: false, code: 'document_retry_network_locked', message: 'استخراج البيانات غير مفعّل حالياً.' } } };
  const diagnostic = clean.match(/^\/document-batches\/([^/]+)\/diagnostics$/);
  if (diagnostic) return { handled: true, response: { data: { schema_version: 'document-diagnostics-v1', generated_at: now, scope: { tenant_id: 'demo-tenant', branch_id: 'demo-branch' }, document: { batch_id: diagnostic[1], workflow_status: 'failed', processing_status: operations.data[0].processing_status, files: [{ file_id: operations.data[0].file.id, scan_status: 'clean', purged_at: null }], processing_runs: [{ run_id: operations.data[0].runs[0].id, stage: 'extraction', status: 'failed', attempt_count: 1, safe_error_code: 'extraction_failed', safe_error_message: 'فشل الاستخراج بعد استنفاد المحاولات المسموح بها.' }], linked_transactions: [] }, retention: { enabled: true, retention_days: 365, active_hold_count: 1 } } } };
  if (clean === '/platform/document-operations') return { handled: true, response: { data: { runtime: { queue_configured: false, worker_status: 'offline', worker_last_seen_at: null, queued_runs: 1, running_runs: 0, failed_runs: 1 }, batches_by_status: [{ status: 'failed', count: 1 }], runs_by_status: [{ status: 'failed', count: 1 }], retention: operations.retention, retention_runs: [{ id: 'rr4eb89c9-1a75-4583-9e03-1cff77a65c08', dry_run: true, status: 'completed', cutoff_at: now, scanned_count: 3, eligible_count: 0, purged_count: 0, skipped_count: 3, after_file_id: null, next_after_file_id: 'f6eb89c9-1a75-4583-9e03-1cff77a65c08', created_at: now }] } } };
  if (clean === '/platform/document-usage') return { handled: true, response: { data: { ...usage, per_tenant: [{ tenant_id: 'demo-tenant', operations: 2, pages: 4, input_tokens: 860, output_tokens: 212 }], per_provider_model: usage.by_provider_model } } };
  if (clean === '/platform/document-diagnostics') return { handled: true, response: { data: { schema_version: 'document-diagnostics-v1', runtime: { queue_configured: false, worker_online: false, scanner_ready: false, provider_configured: false, provider_network_locked: true, runs: { queued: 1, running: 0, failed: 1 } } } } };
  if (clean === '/platform/document-retention-policy' && method === 'PATCH') return { handled: true, response: { data: { retention_days: input.retention_days, enabled: input.enabled } } };
  if (clean === '/platform/document-retention-runs' && method === 'POST') { const afterFileId = typeof input.after_file_id === 'string' ? input.after_file_id : null; return { handled: true, response: { data: { run_id: 'rr4eb89c9-1a75-4583-9e03-1cff77a65c08', dry_run: input.dry_run ?? true, status: 'completed', cutoff_at: now, after_file_id: afterFileId, next_after_file_id: afterFileId === null ? 'f6eb89c9-1a75-4583-9e03-1cff77a65c08' : null, results: { scanned: 3, eligible: 0, purged: 0, skipped: 3 } } } }; }
  return { handled: false };
}
