<?php

namespace App\Support;

enum ApplicationAccessReason: string
{
    case ACCESS_ALLOWED = 'ACCESS_ALLOWED';
    case ACCESS_READ_ONLY = 'ACCESS_READ_ONLY';
    case UNKNOWN_CAPABILITY = 'UNKNOWN_CAPABILITY';
    case CAPABILITY_NOT_BUILT = 'CAPABILITY_NOT_BUILT';
    case NOT_ENTITLED = 'NOT_ENTITLED';
    case ENTITLEMENT_READ_ONLY = 'ENTITLEMENT_READ_ONLY';
    case APPLICATION_DISABLED = 'APPLICATION_DISABLED';
    case APPLICATION_SUSPENDED_READ_ONLY = 'APPLICATION_SUSPENDED_READ_ONLY';
    case DEPENDENCY_NOT_ENTITLED = 'DEPENDENCY_NOT_ENTITLED';
    case DEPENDENCY_DISABLED = 'DEPENDENCY_DISABLED';
    case DEPENDENCY_READ_ONLY = 'DEPENDENCY_READ_ONLY';
    case DEPENDENCY_CYCLE = 'DEPENDENCY_CYCLE';
    case RBAC_DENIED = 'RBAC_DENIED';
}
