import { browser, login, WEB, SEED, API, log } from './lib.mjs';
import { execSync } from 'node:child_process';
execSync('cd /home/user/nibras-app && php artisan cache:clear', { stdio: 'ignore' });
const b = await browser(); const page = await (await b.newContext({ viewport: { width: 1440, height: 1000 } })).newPage(); await login(page);
const tok = await page.evaluate(() => localStorage.getItem('token'));
const api = (m, p, body) => fetch(`${API}/api/commerce/workspace/storefronts/${SEED.storefrontA}${p}`, { method: m, headers: { Authorization: `Bearer ${tok}`, Accept: 'application/json', 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }).then(async (r) => ({ status: r.status, json: await r.json().catch(() => null) }));
for (const o of (await api('GET', '/offers')).json.data) if ((o.product?.id ?? o.product_id) === SEED.products.A2) await api('DELETE', `/offers/${o.id}`);
await page.goto(`${WEB}/commerce/appearance`); await page.waitForSelector('[data-experience-builder]', { timeout: 60000 }); await page.waitForTimeout(3500);
await page.addStyleTag({ content: 'nextjs-portal{display:none!important}' });
await page.getByRole('button', { name: /الصفحة الرئيسية/ }).first().click().catch(() => {}); await page.waitForTimeout(500);
await page.locator('[data-composer-section="offers"]').nth(1).locator('button:not([aria-label])').first().click(); await page.waitForTimeout(1200);
const P = page.locator('[data-selected-section-settings="offers"]');
await P.locator('[data-offer-add]').click(); await page.waitForTimeout(500);
await api('POST', '/offers', { product_id: SEED.products.A2 });
await P.locator(`[data-offer-product-option="${SEED.products.A2}"]`).click(); await P.locator('[data-offer-submit]').click(); await page.waitForTimeout(2500);
log('after 409: form open', await P.locator('[data-offer-form]').count(), '| error shown', await P.locator('[data-offer-field-error="product_id"]').count(), '| selected product kept', await P.locator('[data-offer-selected-product]').count());
await P.locator('[data-offer-cancel]').click(); await page.waitForTimeout(600);
log('after cancel (no manual refresh): A2 row present =', await P.locator('[data-offers-option]', { hasText: 'منتج أ٢' }).count());
await b.close();
