import { browser, login, WEB, OUT, SEED, log, checks } from './lib.mjs';
const b = await browser(); const ctx = await b.newContext({ viewport: { width: 1440, height: 1000 } }); const page = await ctx.newPage();
const reqs = []; const errs = [];
page.on('request', (r) => { if (r.url().includes('/api/commerce')) reqs.push(`${r.method()} ${r.url().replace(/^.*\/api\//,'').replace(SEED.storefrontA,'{A}')}`); });
page.on('console', (m) => m.type() === 'error' && errs.push(m.text().slice(0, 140)));
const { ok, finish } = checks();
const shot = (n) => page.screenshot({ path: `${OUT}/${n}.png`, fullPage: false });
const panel = () => page.locator('[data-selected-section-settings="offers"]');
const canvasSecs = () => page.locator('[data-preview-canvas] section[aria-labelledby^="preview-offers-"]');
const cardNames = async (i) => canvasSecs().nth(i).locator('[data-home-offer-card]').evaluateAll(els => els.map(e => e.innerText.replace(/\n/g,' | ').slice(0,120)));
const selNames = async () => panel().locator('[data-offers-selected-item]').evaluateAll(els => els.map(e => e.innerText.split('\n')[0]));
async function addOffers() { await page.locator('[data-add-section]').click(); await page.locator('[data-picker-option="offers"]').click(); await page.waitForTimeout(1500); }
async function createOffer(pid) { await panel().locator('[data-offer-add], [data-offer-create-empty]').first().click(); await panel().locator(`[data-offer-product-option="${pid}"]`).click(); await panel().locator('[data-offer-submit]').click(); await page.waitForTimeout(1500); }
async function toggle(name) { await panel().locator('[data-offers-option]', { hasText: name }).first().locator('button[aria-pressed]').first().click().catch(async()=>{ await panel().locator('[data-offers-option]', { hasText: name }).first().click(); }); await page.waitForTimeout(300); }

await login(page);
await page.goto(`${WEB}/commerce/appearance`); await page.waitForSelector('[data-experience-builder]', { timeout: 60000 });
await page.getByRole('button', { name: 'إنشاء أول نسخة' }).waitFor({ timeout: 20000 });
await page.getByPlaceholder(/مثال/).fill('H4-8 QA'); await page.getByRole('button', { name: 'إنشاء أول نسخة' }).click(); await page.waitForTimeout(2500);
await page.getByRole('button', { name: 'الصفحة الرئيسية' }).first().click(); await page.waitForTimeout(600);
log('1. add Offers section #1 + create A, A2 via merchant CRUD');
await addOffers(); await createOffer(SEED.products.A); await createOffer(SEED.products.A2);
const listTxt = await panel().innerText();
ok(/منتج أ — خصم حقيقي وبالمخزون[\s\S]*ظاهر الآن/.test(listTxt), 'A live'); 
await shot('20-created');
log('2. select A, A2, B(hidden); reorder');
await toggle('منتج أ — خصم'); await toggle('منتج أ٢'); await toggle('منتج ب');
log('   selected:', JSON.stringify(await selNames()));
log('   canvas  :', JSON.stringify(await cardNames(0)));
await page.screenshot({ path: `${OUT}/21-selected.png` });
log('   reorder: move A2 up');
await panel().getByRole('button', { name: /نقل العرض لأعلى: منتج أ٢/ }).click(); await page.waitForTimeout(300);
ok(JSON.stringify((await selNames()).slice(0,2)) === JSON.stringify(['منتج أ٢ — خصم حقيقي وبالمخزون','منتج أ — خصم حقيقي وبالمخزون']), 'selected order A2,A,B');
let c0 = await cardNames(0); ok(c0.length === 2 && c0[0].includes('أ٢') && c0[1].includes('منتج أ —'), 'canvas S1 order A2,A (hidden B omitted)');
log('3. second Offers instance: A, then A2 (independent)');
await page.locator('[data-add-section]').click(); await page.locator('[data-picker-option="offers"]').click(); await page.waitForTimeout(1500);
ok(await canvasSecs().count() === 2, 'two Offers sections on canvas');
await toggle('منتج أ — خصم'); await toggle('منتج أ٢');
log('   S2 selected:', JSON.stringify(await selNames()));
let c1 = await cardNames(1); ok(c1.length === 2 && c1[0].includes('منتج أ —') && c1[1].includes('أ٢'), 'canvas S2 order A,A2');
c0 = await cardNames(0); ok(c0[0].includes('أ٢'), 'S1 unchanged (A2,A)');
await shot('22-two-instances');
log('4. save draft + reload');
await page.getByRole('button', { name: 'حفظ المسودة' }).click(); await page.waitForTimeout(2500);
await page.reload(); await page.waitForSelector('[data-experience-builder]', { timeout: 60000 }); await page.waitForTimeout(3000);
await page.getByRole('button', { name: 'الصفحة الرئيسية' }).first().click().catch(()=>{}); await page.waitForTimeout(1500);
ok(await canvasSecs().count() === 2, 'reload: two Offers sections persisted');
c0 = await cardNames(0); c1 = await cardNames(1);
ok(c0[0]?.includes('أ٢') && c0[1]?.includes('منتج أ —'), 'reload: S1 order A2,A'); ok(c1[0]?.includes('منتج أ —') && c1[1]?.includes('أ٢'), 'reload: S2 order A,A2');
await shot('23-after-reload');
log('5. edit/deactivate/reactivate A');
const selectSection = async (i) => { await page.locator('[data-composer-section="offers"]').nth(i + 1).locator('button:not([aria-label])').first().click(); await page.waitForTimeout(700); };
await selectSection(0);
log('   panel count', await panel().count(), 'composer li:', await page.locator('[data-composer-section]').evaluateAll(e=>e.map(x=>x.dataset.composerSection+':'+x.className.includes('primary'))).then(a=>a.join(',')));
await shot('23b-after-select');
const wrapOf = (name) => panel().locator('[data-offers-option]', { hasText: name }).first().locator('xpath=ancestor::*[.//*[@data-offer-edit]][1]');
const rowA = () => wrapOf('منتج أ — خصم');
await rowA().locator('[data-offer-edit]').click(); await panel().getByLabel('العرض مفعّل').uncheck(); await panel().locator('[data-offer-submit]').click(); await page.waitForTimeout(1800);
log('   A row:', (await rowA().innerText()).replace(/\n/g,' | ').slice(0,110));
ok((await cardNames(0)).length === 1 && (await cardNames(1)).length === 1, 'deactivated A disappears from BOTH canvases (shared catalog)');
await shot('24-deactivated');
await rowA().locator('[data-offer-edit]').click(); await panel().getByLabel('العرض مفعّل').check(); await panel().locator('[data-offer-submit]').click(); await page.waitForTimeout(1800);
ok((await cardNames(0)).length === 2 && (await cardNames(1)).length === 2, 'reactivated A returns in both');
log('6. save + PUBLISH (normal AWJ flow)');
await page.getByRole('button', { name: 'حفظ المسودة' }).click(); await page.waitForTimeout(2000);
await page.locator('[data-publish]').click(); await page.waitForTimeout(800);
await shot('25-publish-dialog');
await page.locator('[data-publish-confirm-submit]').click(); await page.waitForTimeout(3500);
await shot('26-published');
const pub = await b.newContext({ viewport: { width: 1440, height: 1000 } });
await pub.close();
// ---- Published read through REAL host resolution (browser maps a.h48.test -> 127.0.0.1; Host header is genuine)
const b2 = await browser(['--host-resolver-rules=MAP *.h48.test 127.0.0.1']);
const pp = await (await b2.newContext({ viewport: { width: 1440, height: 1000 } })).newPage();
const pubReqs = []; pp.on('request', (r) => { if (/\/store\/v1\/offers/.test(r.url())) pubReqs.push(r.url()); });
const readPub = async (host) => { await pp.goto(`http://${host}:3001/sa/ar`, { waitUntil: 'networkidle', timeout: 90000 }); const secs = pp.locator('section[aria-labelledby]').filter({ has: pp.locator('[data-offer-card]') });
  const out = []; for (let i = 0; i < await secs.count(); i++) out.push(await secs.nth(i).locator('[data-offer-card]').evaluateAll(els => els.map(e => ({ t: e.innerText.replace(/\n/g,' | '), price: e.querySelector('[data-offer-price]')?.textContent, ref: e.querySelector('[data-offer-reference]')?.textContent, badge: e.querySelector('[data-offer-badge]')?.textContent })))); return out; };
const pubA = await readPub('a.h48.test'); await pp.screenshot({ path: `${OUT}/27-published-A.png`, fullPage: true });
log('   published A sections:', JSON.stringify(pubA.map(s => s.map(c => c.t.slice(0, 60)))));
ok(pubA.length === 2, 'published has 2 Offers sections');
ok(pubA[0]?.length === 2 && pubA[0][0].t.includes('أ٢') && pubA[0][1].t.includes('منتج أ —'), 'published S1 order A2,A (parity with Canvas)');
ok(pubA[1]?.length === 2 && pubA[1][0].t.includes('منتج أ —') && pubA[1][1].t.includes('أ٢'), 'published S2 order A,A2 (parity)');
log('   published fields:', JSON.stringify(pubA[0]?.map(c => [c.price, c.ref, c.badge])));
ok(!JSON.stringify(pubA).includes('منتج ب'), 'hidden B (ATS) not published');
log('   public /store/v1/offers requests per page load:', pubReqs.length);
const pubB = await readPub('b.h48.test'); log('   storefront B sections:', JSON.stringify(pubB.map(s => s.length))); ok(!JSON.stringify(pubB).includes('أ٢') , 'storefront B shows none of A offers');
const pubU = await readPub('unverified.h48.test').catch(e => 'ERR'); log('   unverified host:', JSON.stringify(pubU));
ok(Array.isArray(pubU) && pubU.length === 0, 'unverified host: no offers rendered');
await b2.close();
log('7. draft-only change must not leak before publish');
await page.locator('[data-version-create-draft-from-published]').click(); await page.waitForTimeout(3000); await shot('26b-draft-from-published');
await selectSection(0);
await panel().locator('[data-offers-selected-item]', { hasText: 'أ٢' }).getByRole('button', { name: /إزالة/ }).click(); await page.waitForTimeout(400);
await page.getByRole('button', { name: 'حفظ المسودة' }).click(); await page.waitForTimeout(2500);
ok((await cardNames(0)).length === 1, 'draft S1 now has 1 card');
const b3 = await browser(['--host-resolver-rules=MAP *.h48.test 127.0.0.1']); const p3 = await (await b3.newContext()).newPage();
await p3.goto('http://a.h48.test:3001/sa/ar', { waitUntil: 'networkidle', timeout: 90000 });
const n = await p3.locator('section[aria-labelledby]').filter({ has: p3.locator('[data-offer-card]') }).first().locator('[data-offer-card]').count();
ok(n === 2, 'published S1 still has 2 cards (draft did not leak)'); await b3.close();
log('8. delete offer A2 -> cleans references in BOTH instances');
await wrapOf('منتج أ٢').locator('[data-offer-delete]').click();
await shot('28-delete-confirm');
await panel().getByRole('alertdialog').locator('[data-offer-delete-confirm-button]').click(); await page.waitForTimeout(2000);
await selectSection(1); const selS2 = await selNames(); log('   S2 selected after delete:', JSON.stringify(selS2));
ok(selS2.length === 1 && !selS2[0].includes('أ٢'), 'A2 removed from S2 selection too');
ok((await cardNames(0)).length === 1 && (await cardNames(1)).length === 1, 'canvases: A2 gone from both');
await shot('29-after-delete');
await b.close();
finish(); log('errs', [...new Set(errs)].map(e=>e.slice(0,90)).join('\n')); log('REQS', reqs.length); log(reqs.join('\n'));
