import { browser, login, WEB, OUT, log } from './lib.mjs';
const locale = process.env.LOCALE ?? 'ar'; const w = Number(process.env.WIDTH ?? 390);
const b = await browser(); const ctx = await b.newContext({ viewport: { width: w, height: 844 }, isMobile: true, hasTouch: true }); await ctx.addCookies([{ name: 'locale', value: locale, url: WEB }]);
const page = await ctx.newPage(); await login(page); await ctx.addCookies([{ name: 'locale', value: locale, url: WEB }]);
await page.goto(`${WEB}/commerce/appearance`); await page.waitForSelector('[data-experience-builder]', { timeout: 60000 }); await page.waitForTimeout(3500);
await page.addStyleTag({ content: 'nextjs-portal{display:none!important}' });
await page.getByRole('button', { name: locale === 'ar' ? 'الأقسام' : /^Sections$/ }).click(); await page.waitForTimeout(800);
const dlg = page.getByRole('dialog'); log('dialog count', await dlg.count());
log('rows:', JSON.stringify(await dlg.locator('[data-composer-section]').evaluateAll(e => e.map(x => x.dataset.composerSection))));
await page.screenshot({ path: `${OUT}/m-${locale}-${w}-sheet.png` });
await dlg.locator('[data-composer-section="offers"]').nth(1).locator('button:not([aria-label])').first().click(); await page.waitForTimeout(1200);
await page.screenshot({ path: `${OUT}/m-${locale}-${w}-offers.png` });
const P = dlg.locator('[data-selected-section-settings="offers"]');
const measure = async (tag) => { const o = await page.evaluate(() => { const d = document.querySelector('[role=dialog]'); return { doc: document.documentElement.scrollWidth - document.documentElement.clientWidth, dlg: d ? d.scrollWidth - d.clientWidth : null }; }); log(tag, 'overflow(px) doc/dialog:', o.doc, o.dlg); return o; };
await P.scrollIntoViewIfNeeded(); await page.waitForTimeout(500);
await P.locator('[data-offers-selected]').first().scrollIntoViewIfNeeded().catch(()=>{}); await page.screenshot({ path: `${OUT}/m-${locale}-${w}-panel-selected.png` }); await measure('selected+list');
await P.locator('[data-offer-add]').scrollIntoViewIfNeeded(); await page.screenshot({ path: `${OUT}/m-${locale}-${w}-panel-list.png` });
await P.locator('[data-offer-add]').click(); await page.waitForTimeout(800);
await P.locator('[data-offer-form]').scrollIntoViewIfNeeded(); await page.screenshot({ path: `${OUT}/m-${locale}-${w}-form.png` }); await measure('create form');
log('dialog count with form open:', await page.getByRole('dialog').count());
const sb = await P.locator('[data-offer-submit], [data-offer-cancel]').first().boundingBox(); log('submit/cancel height', sb?.height);
await P.locator('[data-offer-starts]').scrollIntoViewIfNeeded(); await page.screenshot({ path: `${OUT}/m-${locale}-${w}-form-dates.png` });
await P.locator('[data-offer-cancel]').click(); await page.waitForTimeout(500);
await P.locator('[data-offer-delete]').first().scrollIntoViewIfNeeded(); await P.locator('[data-offer-delete]').first().click(); await page.waitForTimeout(600);
await P.getByRole('alertdialog').scrollIntoViewIfNeeded(); await page.screenshot({ path: `${OUT}/m-${locale}-${w}-delete.png` }); await measure('delete confirm');
log('alertdialog count', await P.getByRole('alertdialog').count(), 'dialog count', await page.getByRole('dialog').count());
await page.keyboard.press('Escape'); await page.waitForTimeout(400); log('after Escape alertdialog', await P.getByRole('alertdialog').count(), 'sheet still open', await page.getByRole('dialog').count());
await b.close();
