"use client";

/**
 * CUST-HV V4b — Canvas preview URL for a `MediaRef` (signed workspace URLs).
 *
 * Read-only: it resolves the asset and, for a framed usage, **reads** the
 * derivative status — it never generates (generation is the field's job, on an
 * explicit edit). The framed rendition is used when ready; otherwise the base
 * preview, so the Canvas never shows a broken image while a frame processes.
 * The URL is editor-only, signed and short-lived; it is never written anywhere.
 *
 * A framing the merchant has just applied is generated by the field after a debounce, so the first
 * read can see it `absent`; when that generation completes (`onUsageGenerated`) the framed rendition
 * is read again, so the Canvas shows the saved framing rather than the unframed original.
 */
import { useEffect, useState } from "react";
import {
  fetchStorefrontMediaAsset,
  mediaRefTransform,
  usageNeedsDerivatives,
  usageStatus,
} from "@/modules/commerce-workspace/storefront-media";
import type { MediaRef } from "../presentation/media-ref";
import { onUsageGenerated, pickPreviewUrl, usageKey } from "./use-usage-readiness";

const POLL_MS = 2000;
const MAX_POLLS = 30;

export function useMediaRefPreview(ref: MediaRef | null): string | null {
  const key = ref ? JSON.stringify([ref.mediaId, mediaRefTransform(ref)]) : "";
  const [url, setUrl] = useState<string | null>(null);

  useEffect(() => {
    if (!ref) {
      setUrl(null);
      return;
    }
    const controller = new AbortController();
    let live = true;
    (async () => {
      try {
        const asset = await fetchStorefrontMediaAsset(ref.mediaId, controller.signal);
        if (!live) return;
        const base = asset?.previewUrl ?? asset?.thumbnailUrl ?? null;
        setUrl(base);
        if (asset && usageNeedsDerivatives(ref)) {
          // A usage another tab/user is generating (`processing`) is followed to completion (bounded);
          // `absent` is picked up by the in-page `onUsageGenerated` signal below.
          for (let attempt = 0; attempt <= MAX_POLLS; attempt += 1) {
            const status = await usageStatus(ref.mediaId, mediaRefTransform(ref));
            if (!live) return;
            const framed = status.state === "ready" ? pickPreviewUrl(status) : null;
            if (framed) setUrl(framed);
            if (status.state !== "processing") break;
            await new Promise((resolve) => setTimeout(resolve, POLL_MS));
            if (!live) return;
          }
        }
      } catch {
        if (live) setUrl(null);
      }
    })();
    return () => {
      live = false;
      controller.abort();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- `key` is the identity of `ref`
  }, [key]);

  useEffect(() => {
    if (!ref || !usageNeedsDerivatives(ref)) return;
    let live = true;
    const watched = usageKey(ref);
    const stop = onUsageGenerated((generated) => {
      if (generated !== watched) return;
      void usageStatus(ref.mediaId, mediaRefTransform(ref))
        .then((status) => {
          const framed = live && status.state === "ready" ? pickPreviewUrl(status) : null;
          if (framed) setUrl(framed);
        })
        .catch(() => undefined);
    });
    return () => {
      live = false;
      stop();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- `key` is the identity of `ref`
  }, [key]);

  return url;
}
